apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: capstone
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


