kind: PersistentVolume 
apiVersion: v1 
metadata: 
 name: pv-mysql
 labels:
    type: local 
spec: 
  storageClassName: manual 
  capacity: 
    storage: 2Gi 
  accessModes: 
    - ReadWriteMany
  hostPath: 
    path: "/mnt/mysql"
